[package]
name = "pulse"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "0.17.0"
futures = "0.3"

[lib]
name = "pulse"
crate-type = ["rlib", "cdylib"]

