site_name: hyperdata - Data.Collection for Python
repo_url: https://github.com/reiase/hyperdata

theme:
  name: "material"

plugins:
  - search
  - i18n:
      languages:
        en: "English"
        zh: "中文"
      default_language: 'en'
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: yes
            merge_init_into_class: yes
            show_submodules: no

nav:
  - Home: index.md
  - Reference: reference.md

watch:
    - hyperdata

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: 中文
      link: /zh/
      lang: zh
